name: Lint

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 21]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: type-check
        run: npm run tsd
